services:
  - type: web
    name: customer-churn-django
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py collectstatic --noinput
    startCommand: gunicorn firstproject.wsgi:application